name: Feature Request
description: Suggest a new feature for OhMyShot
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! We appreciate your feedback.
        
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: |
        A clear description of what you want...
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem it Solves
      description: What problem does this feature solve? Why do you need it?
      placeholder: |
        I'm always frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples?
